### ISSUE TITLE
Clipboard does not work

### ISSUE THREAD

**Issue by funnym0nk3y** [debauchee/barrier#103]
### Operating Systems ###

Server: Win10 64bit

Client: Win10 64bit

### Barrier Version ###

2.1.0

### Steps to reproduce bug ###

When running the software at both PCs there ist a problem with the clipboard. As the configuration states, there ist the possibility to transfer files via Drag-n-Drop between the machines. But when trying to do so, grabbing the file on the client works, but the release does not on the server. Also, when cutting on the client, the server does not recieve anything in it's clipboard. This problem existed also in Synergy.

**Comment by nsk7even** [comment]
You may check my issue where I found out that the automatic elevation on the client side was responsible for the clipboard stopped working: https://github.com/debauchee/barrier/issues/141

**Comment by panaut0lordv** [comment]
It was also happening to me, both on latest Barrier and Synergy release Synergy_v1.9.0_rc3.msi (just copied that from the Windows VM via Barrier client! I am so happy :D).

However, while workaround works which means I'm no longer using Barrier LOCAL SYSTEM service (I've put it in disabled state for now) but rather "synergyc.exe IP" in my AppData/Roaming/Ms/Win/Start Menu/Programs/Startup I still have an issue.
As you might guess such a "solution" no longer allows me to click inside elevated popups or login back to my user's session (e.g. after using RDP to click an elevated popup).
Any tips on how to deal with it?
Preferably with software workaround, not simply keeping dedicated USB mouse passed through to my VM.

BTW I'm reading through this file https://github.com/debauchee/barrier/blob/master/src/lib/platform/MSWindowsClipboard.h
and one thing makes me wonder about that behaviour… because what I actually got wasn't a clipboard that wasn't updated - it was an empty clipboard. Does that help?

**Comment by andrejrcarvalho** [comment]
I'm with the same problem. I'm runnig the server in a Windows 10 and the client on a Ubuntu. I have notice that the clipboard stops working when I copy something from de client.

**Comment by jamesgeddes** [comment]
Same here, running Ubuntu and Win10 but cannot share clipboard between them. Would be super helpful if this worked.

**Comment by genebeck** [comment]
Similar problem here.  Version 2.3.2 Windows 10 host, Windows 10 and Linux Mint 19 clients.  Clipboard works for a while then no updating.  Restart the Barrier using the GUI on the server then all works for and hour or 2.  Not drag or drop or copy files.  This is using the clipboard for just text.

This is very irritating.

**Comment by shymega** [comment]
Closing in favour of #855, as it has a similar mechanic to drag and drop -- in this case, clipboard sync of files.

**Comment by jmrenouard** [comment]
Hi,

This issue is still present in 2.4.0
Changing setting Elevate to As needed on the server side solves this issue

But iI don't figure it out why this is impacting copy/paste feature

Thanks for this great piece of software, Barrier is awesome !

Jean-Marie

**Comment by juankb1024** [comment]
I'm having the same issue in 2.4.0.

Using MacOS 12.4 Server and Windows 10 Client.

My problem is that the MacOS server does not have the "Elevate to" setting. Is this setting missing form the MacOS GUI?

Is there a way to force this setting in MacOS to see if it's related?

**Comment by JoeCodeswell** [comment]
For me,
  Barrier-Server: Windows 10
  Barrier-Client: macOS 10.15.7

The clipboard works for a while & then stops working.

My WORKAROUND is to Reload the Server. 

RESULT the clipboard starts working again.

Thanks for the GREAT PRODUCT.

Joe

**Comment by NaveenBen** [comment]
vvvvvvvvvvvvvVVVVVVVVVVVVVVVvvvvvvvv

**Comment by AdamStepinski0** [comment]
I had copy paste not working on Windows. I had two server instances running
UPDATE: two server instances were reason for problem with copy paste

**Comment by shymega** [comment]
> I had copy paste not working on Windows. I had two server instances running

Barrier isn't maintained anymore. But more importantly, that's not how the architecture works - you need a server and client(s).

**Comment by jamesgeddes** [comment]
@shymega When was the decision taken to stop maintaining barrier? I cannot see any advisements on that. Could it become an Apache Software Foundation or Linux Foundation project?

**Comment by shymega** [comment]
> @shymega When was the decision taken to stop maintaining barrier? I cannot see any advisements on that. Could it become an Apache Software Foundation or Linux Foundation project?

That decision was years back. We aren't obliged to advertise, and I explained numerous times on this tracker, but we won't be advertising on the Barrier repo. You can see the explanation [here](https://github.com/input-leap/input-leap/issues/1414).

Input Leap is currently working on resolving the numerous bugs that have accumulated in Barrier, notably memory and CPU leaks, and updating to Qt 6 so that ARM64 can be supported on macOS.

And I don't think ASF or Linux Foundation will take Barrier on. In any case, Input Leap has diverged from Barrier and put more resources in, so it's not worth it. The differences are numerous, and it would be a waste of manpower.
