### ISSUE TITLE
Logitech Flow and Barrier Conflict

### ISSUE THREAD

**Issue by rachelkd** [debauchee/barrier#1472]
### What happened?

I'd like to preface this by saying I don't know much about development, so if this is vague/not helpful, sorry.

I use 2 mouses on my client side: a Razer mouse and Logitech MX Anywhere 2S. Logitech uses Flow which copies text from one computer to another connected through Bluetooth. I noticed that I cannot copy text from my server side (Windows PC) to client (MacOS) when using my Logitech mouse when both Flow and Barrier are turned on. I can, however, copy text from the client back to the server with no problem. When I try to paste text from the server to the client, it is just empty. It works fine with my other mouse though. Does anyone have a fix for this that doesn't require turning one program off? Flow works better because the Bluetooth makes mouse tracking more reliable than Barrier, but I also like to have 1 keyboard connected to both computers.

### Version

v2.4.0

### What OSes are you seeing the problem on? (Check all that apply)

Windows, macOS

### What OS versions are you using?

Windows Version 10.0.19042 Build 19042,
MacOS Monterey

### Relevant log output

```shell
[2021-12-05T16:31:14] INFO: switch from "PC" to "MacBook-Pro" at 1439,487
[2021-12-05T16:31:14] INFO: leaving screen
[2021-12-05T16:31:14] WARNING: failed to open clipboard: 5
[2021-12-05T16:31:14] WARNING: failed to open clipboard: 5
[2021-12-05T16:31:15] INFO: screen "MacBook-Pro" grabbed clipboard 0 from "PC"
[2021-12-05T16:31:15] INFO: screen "MacBook-Pro" grabbed clipboard 1 from "PC"
[2021-12-05T16:31:15] WARNING: failed to open clipboard: 5
```

**Comment by ghost** [comment]
Similar issue except I only installed logi options and it killed my barrier connection

**Comment by InfernalWAVE** [comment]
why even use logi flow? barrier allows for copy paste between server and client. so go into logi options+, disable flow on any machines you will be using barrier with, and you're good to go. logi flow performs significantly worse than barrier anyways, with major delay switching between machines

edit: I see that you mentioned Bluetooth improves mouse tracking. in my experience, using logic flow is infinitely more frustrating than barrier due to the delay on switch. but it will depend on your use case I suppose

**Comment by mystcreater** [comment]
> why even use logi flow? barrier allows for copy paste between server and client. so go into logi options+, disable flow on any machines you will be using barrier with, and you're good to go. logi flow performs significantly worse than barrier anyways, with major delay switching between machines
> 
> edit: I see that you mentioned Bluetooth improves mouse tracking. **in my experience, using logic flow is infinitely more frustrating than barrier due to the delay on switch. but it will depend on your use case I suppose**

Finally, someone who say the same thing than me. I discover Barrier only today and there is no comparison between Logitech and Barrier in term of speed. I was to the point of stopping using both computers at the same time because of the delay each time I switched from one to another. With Barrier, there is no issue at all. Barrier still has other problem like typing French accents in the "Client"; the computer used as client from Barrier. I had to use AutoHotKey and Keyboard Maestro with US keyboard to get rid of the problem. It's not perfect but it is much better than the delay problem. Note that with Logitech, I also had a very big problem where a couple of times a day, the Opt/Win key stuck when switching and the only way to get rid of this problem was to press this key once when the problem arrived. Again, no similar problem with Barrier. Finally, I'm not able to copy and paste a file from one to another with Barrier but I can with Logitech. But man, the delay is the top pain in the ass. How could Logitech a so big company cannot compete with an open source?

**Comment by nuffin** [comment]
**Update**: I've found the solution.

I set the main display scale on Windows to 100%, and then it works, even when Logi Flow is ON.

So, I'm back. [:lol:]

Hope this helps you guys too.

----

I'll draw back to logi flow.  Though it's a little bit slow, but it works.

When I disabled "Flow" in Logi Options+, and start both barrier server and client, the cursor goes away, and I cannot find out where it is.

Server: Windows 11 Pro 23H2, screen: 3840x2160, scale 200%
Cilent: macOS sonoma 14.5 on MacBook pro (intel), dual monitor. screen: 2048x1280 (native), 1920x1080 (external)

BTW: When server is running on macOS machine and client is on Windows, they work, but with a little bit keyboard input delay, especially when CPU load on one of them load high. Now I'm switching mouse and keyboard via bluetooth switches when I need the keyboard.

**Comment by a4840639** [comment]
I had this exact issue with Deskflow and I almost thought I went crazy
The weird thing is I had both working side by side (flow is only triggered by holding ctrl and I almost never use it) without any issue for months but then the issue just suddenly appears
Maybe it does have something to do with the display layout (I was trying a lot of things with virtual display / remote desktop)

**Comment by nbolton** [comment]
>I had this exact issue with Deskflow

Barrier is downstream of Deskflow, so that makes sense.

Do you know if there's an upstream bug?
