### ISSUE TITLE
100% CPU use on MacOS 10.13.6

### ISSUE THREAD

**Issue by WreckWren** [debauchee/barrier#629]
Sadly there's not much info I can offer here - Barrier uses 100% CPU after about 5 minutes of running, even with no other servers on the network, and continues to do so until it is closed.

**Comment by IPWright83** [comment]
I've been using barrier for a couple of weeks, it was running pretty much stably but I'm now noticing huge CPU usage in Windows 10 x64 too.

v2.3.2-snapshot-210c2b70

**Comment by simons-public** [comment]
Which version are you using? I've got a build posted from the #648 pull request that changes how the app bundle is packaged and uses recent versions of Qt and OpenSSL [if you want to try it](https://github.com/simons-public/barrier/releases/tag/use-macdeployqt).

**Comment by galkinvv** [comment]
> it was running pretty much stably but I'm now noticing huge CPU usage in Windows 10 x64 too.
> 
> v2.3.2-snapshot-210c2b70

And about cpu usage on windows - there is 2 PRs since that release that should improve the situation:
#557 (Merged)
#656 (Just created, not well-tested yet)

The windows binaries with both fixes are currently available in #656 artifacts at https://dev.azure.com/debauchee/Barrier/_build/results?buildId=167&view=artifacts&type=publishedArtifacts

**Comment by p12tic** [comment]
This bug should be fixed now.
