### ISSUE TITLE
Next Step: Patchwork

### ISSUE THREAD

**Issue by walker0643** [debauchee/barrier#7]
Barrier needs to catch up on some of the patches from other synergy forks and from synergy itself. Any patches that you think should be incorporated are to be added here. Please use this as a meta-issue by creating one issue per patch and adding a comment to it referencing this one. Thanks!

**Comment by DragoonAethis** [comment]
I've created [a list of all Synergy forks on GitHub](https://github.com/DragoonAethis/SynergyForks) which are still linked to the upstream repo and were pushed to at least once since their creation OR have some stars/watchers. It might help with finding forks with commits ready to be pulled, but the list needs to be filtered first, as there are ~200 repos which match those requirements. (Also the GitHub API seems to be a bit bugged and reports the number of watchers == the number of stars, but I've asked support to look at that, so I'll regenerate the list soon.)

**Comment by walker0643** [comment]
Closing at 2.0 release. My thanks to all contributors!
