### ISSUE TITLE
Windows Uninstall

### ISSUE THREAD

**Issue by bobsfriend** [debauchee/barrier#914]
When I try to uninstall barrier it says that not everything can be removed. When I reinstall it, it has the same config as before I unistalled it. I uninstalled it again and this time I deleted the program files folder as well as the AppData/local folder.

Uninstall Barrier

What I expect to happen is it removes everything including the configuration file.

 - OS: Windows 10
- Barrier version 2.3.3

**Comment by bobsfriend** [comment]
The reason I wanted to uninstall barrier is because my machines wouldn't connect. I ended up just having to add aliases to the screens, which I didn't have to do the last time I set up barrier. It is now working wonderfully.

**Comment by dzigner** [comment]
I cannot uninstall the configuration file. I uninstall and reinstall, and the config is as it was in previous install. I tried the above steps - uninstalling, deleting from program folder and user folder, also removing the registry entry under software.
Nothing helps.
I need to uninstall, and then do a clean install of Barrier, because right now, it stays stuck on barrier is starting. I'm on Windows 11 machine as server.
